# Generated by Django 6.0.1 on 2026-01-10 13:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_venta_cantidad_remove_venta_precio_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingreso',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='precio_costo_total',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='precio_costo_unitario',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='producto',
        ),
        migrations.AddField(
            model_name='ingreso',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='DetalleIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_compra', to='inventario.ingreso')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
    ]
