# Generated by Django 6.0.1 on 2026-01-10 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_remove_ingreso_cantidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleingreso',
            old_name='compra',
            new_name='ingreso',
        ),
    ]
