# Generated by Django 6.0.1 on 2026-01-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_rename_compra_detalleingreso_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('cta_corriente', 'Cta. Corriente')], default='efectivo', max_length=20),
        ),
    ]
