# Generated by Django 6.0.1 on 2026-01-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_producto_codigo_barras_producto_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_por_peso',
            field=models.BooleanField(default=False, verbose_name='¿Se vende por peso? (Kg)'),
        ),
        migrations.AlterField(
            model_name='detalleingreso',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=3, default=5.0, max_digits=10),
        ),
    ]
