# Generated by Django 6.0.1 on 2026-01-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_producto_es_por_peso_alter_detalleingreso_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='contenido_neto',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Contenido (Ej: 500g)'),
        ),
    ]
